#!/bin/bash

JENKINS_PLUGIN_INSTALL="/usr/local/bin/install-plugins.sh"

${JENKINS_PLUGIN_INSTALL} ace-editor
${JENKINS_PLUGIN_INSTALL} ant
${JENKINS_PLUGIN_INSTALL} antisamy-markup-formatter
${JENKINS_PLUGIN_INSTALL} apache-httpcomponents-client-4-api
${JENKINS_PLUGIN_INSTALL} authentication-tokens
${JENKINS_PLUGIN_INSTALL} bitbucket
${JENKINS_PLUGIN_INSTALL} bouncycastle-api
${JENKINS_PLUGIN_INSTALL} branch-api
${JENKINS_PLUGIN_INSTALL} build-name-setter
${JENKINS_PLUGIN_INSTALL} build-pipeline-plugin
${JENKINS_PLUGIN_INSTALL} build-timeout
${JENKINS_PLUGIN_INSTALL} build-user-vars-plugin
${JENKINS_PLUGIN_INSTALL} cloudbees-folder
${JENKINS_PLUGIN_INSTALL} command-launcher
${JENKINS_PLUGIN_INSTALL} conditional-buildstep
${JENKINS_PLUGIN_INSTALL} config-file-provider
${JENKINS_PLUGIN_INSTALL} credentials
${JENKINS_PLUGIN_INSTALL} credentials-binding
${JENKINS_PLUGIN_INSTALL} dashboard-view
${JENKINS_PLUGIN_INSTALL} display-url-api
${JENKINS_PLUGIN_INSTALL} docker-commons
${JENKINS_PLUGIN_INSTALL} docker-workflow
${JENKINS_PLUGIN_INSTALL} durable-task
${JENKINS_PLUGIN_INSTALL} email-ext
${JENKINS_PLUGIN_INSTALL} embeddable-build-status
${JENKINS_PLUGIN_INSTALL} external-monitor-job
${JENKINS_PLUGIN_INSTALL} git
${JENKINS_PLUGIN_INSTALL} git-client
${JENKINS_PLUGIN_INSTALL} github
${JENKINS_PLUGIN_INSTALL} github-api
${JENKINS_PLUGIN_INSTALL} github-branch-source
${JENKINS_PLUGIN_INSTALL} gitlab-plugin
${JENKINS_PLUGIN_INSTALL} git-parameter
${JENKINS_PLUGIN_INSTALL} git-server
${JENKINS_PLUGIN_INSTALL} gradle
${JENKINS_PLUGIN_INSTALL} handlebars
${JENKINS_PLUGIN_INSTALL} jackson2-api
${JENKINS_PLUGIN_INSTALL} javadoc
${JENKINS_PLUGIN_INSTALL} jdk-tool
${JENKINS_PLUGIN_INSTALL} jquery
${JENKINS_PLUGIN_INSTALL} jquery-detached
${JENKINS_PLUGIN_INSTALL} jsch
${JENKINS_PLUGIN_INSTALL} junit
${JENKINS_PLUGIN_INSTALL} ldap
${JENKINS_PLUGIN_INSTALL} mailer
${JENKINS_PLUGIN_INSTALL} mapdb-api
${JENKINS_PLUGIN_INSTALL} matrix-auth
${JENKINS_PLUGIN_INSTALL} matrix-project
${JENKINS_PLUGIN_INSTALL} maven-plugin
${JENKINS_PLUGIN_INSTALL} mercurial
${JENKINS_PLUGIN_INSTALL} momentjs
${JENKINS_PLUGIN_INSTALL} nodejs
${JENKINS_PLUGIN_INSTALL} pam-auth
${JENKINS_PLUGIN_INSTALL} parameterized-trigger
${JENKINS_PLUGIN_INSTALL} pipeline-build-step
${JENKINS_PLUGIN_INSTALL} pipeline-github-lib
${JENKINS_PLUGIN_INSTALL} pipeline-graph-analysis
${JENKINS_PLUGIN_INSTALL} pipeline-input-step
${JENKINS_PLUGIN_INSTALL} pipeline-milestone-step
${JENKINS_PLUGIN_INSTALL} pipeline-model-api
${JENKINS_PLUGIN_INSTALL} pipeline-model-declarative-agent
${JENKINS_PLUGIN_INSTALL} pipeline-model-definition
${JENKINS_PLUGIN_INSTALL} pipeline-model-extensions
${JENKINS_PLUGIN_INSTALL} pipeline-rest-api
${JENKINS_PLUGIN_INSTALL} pipeline-stage-step
${JENKINS_PLUGIN_INSTALL} pipeline-stage-tags-metadata
${JENKINS_PLUGIN_INSTALL} pipeline-stage-view
${JENKINS_PLUGIN_INSTALL} plain-credentials
${JENKINS_PLUGIN_INSTALL} rebuild
${JENKINS_PLUGIN_INSTALL} repo
${JENKINS_PLUGIN_INSTALL} resource-disposer
${JENKINS_PLUGIN_INSTALL} role-strategy
${JENKINS_PLUGIN_INSTALL} run-condition
${JENKINS_PLUGIN_INSTALL} scm-api
${JENKINS_PLUGIN_INSTALL} script-security
${JENKINS_PLUGIN_INSTALL} ssh
${JENKINS_PLUGIN_INSTALL} ssh-agent
${JENKINS_PLUGIN_INSTALL} ssh-credentials
${JENKINS_PLUGIN_INSTALL} ssh-slaves
${JENKINS_PLUGIN_INSTALL} structs
${JENKINS_PLUGIN_INSTALL} subversion
${JENKINS_PLUGIN_INSTALL} timestamper
${JENKINS_PLUGIN_INSTALL} token-macro
${JENKINS_PLUGIN_INSTALL} windows-slaves
${JENKINS_PLUGIN_INSTALL} workflow-aggregator
${JENKINS_PLUGIN_INSTALL} workflow-api
${JENKINS_PLUGIN_INSTALL} workflow-basic-steps
${JENKINS_PLUGIN_INSTALL} workflow-cps
${JENKINS_PLUGIN_INSTALL} workflow-cps-global-lib
${JENKINS_PLUGIN_INSTALL} workflow-durable-task-step
${JENKINS_PLUGIN_INSTALL} workflow-job
${JENKINS_PLUGIN_INSTALL} workflow-multibranch
${JENKINS_PLUGIN_INSTALL} workflow-scm-step
${JENKINS_PLUGIN_INSTALL} workflow-step-api
${JENKINS_PLUGIN_INSTALL} workflow-support
${JENKINS_PLUGIN_INSTALL} ws-cleanup